disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console_handler:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  error_handler:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: logs/sync_errors.log
    formatter: detailed
    level: ERROR
    maxBytes: 5242880
  file_handler:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: logs/tabula_service.log
    formatter: detailed
    level: INFO
    maxBytes: 10485760
loggers:
  root:
    handlers:
    - console_handler
    level: WARNING
  tabula_cloud_sync:
    handlers:
    - file_handler
    - error_handler
    - console_handler
    level: INFO
    propagate: false
version: 1
