monitoring:
  cpu_threshold_percent: 80
  health_check_interval: 60
  memory_threshold_mb: 500
  performance_metrics: true
service:
  auto_start: true
  description: "Servicio de sincronizaci\xF3n con Tabula Cloud"
  display_name: Cli Tabula Service
  max_restart_attempts: 3
  name: cli_tabula_service
  project_type: package
  restart_on_failure: true
sync:
  batch_processing: true
  cleanup_old_logs: true
  default_interval: 300
  error_threshold: 10
  log_retention_days: 30
  parallel_processing: false
